[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
race_solana = "ATgCyKtLjQy4A2J3GGb2mvr2X3KoDPtDN6RFRLkYpmis"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/naidu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
